tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'kylef/formulae'
tap 'welldan97/updater'
brew 'autoconf'
brew 'automake'
brew 'bazaar'
brew 'gmp'
brew 'isl'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'openssl'
brew 'libevent'
brew 'open-mpi'
brew 'boost', args: ['with-icu4c']
brew 'cctools'
brew 'chisel'
brew 'gmp@4'
brew 'isl@0.12'
brew 'cloog'
brew 'cmake'
brew 'colordiff'
brew 'curl'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'dos2unix'
brew 'entr'
brew 'faac'
brew 'faad2'
brew 'lame'
brew 'git'
brew 'x264'
brew 'xvid'
brew 'ffmpeg'
brew 'fftw'
brew 'flac'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'fluid-synth'
brew 'libpng'
brew 'freetype'
brew 'gdbm'
brew 'libyaml'
brew 'readline'
brew 'ruby'
brew 'ghi'
brew 'gifsicle'
brew 'gnu-typist'
brew 'pinentry'
brew 'gpg-agent'
brew 'libusb'
brew 'libusb-compat'
brew 'gnupg2'
brew 'libtasn1'
brew 'nettle'
brew 'p11-kit'
brew 'gnutls'
brew 'hh'
brew 'lua'
brew 'highlight'
brew 'htop'
brew 'hub'
brew 'hugo'
brew 'icu4c'
brew 'jpeg'
brew 'libtiff'
brew 'libtool'
brew 'perl'
brew 'xz'
brew 'imagemagick'
brew 'isl@0.11'
brew 'oniguruma'
brew 'jq'
brew 'leiningen'
brew 'libao'
brew 'libfreenect'
brew 'libid3tag'
brew 'libmpdclient'
brew 'libogg'
brew 'libsamplerate'
brew 'libsass'
brew 'libvorbis'
brew 'libsndfile'
brew 'libvo-aacenc'
brew 'sqlite'
brew 'python'
brew 'llvm'
brew 'mad'
brew 'mas'
brew 'memcached'
brew 'mercurial'
brew 'minicom'
brew 'mogenerator'
brew 'mpc'
brew 'mpd', restart_service: :changed
brew 'taglib'
brew 'ncmpcpp'
brew 'node'
brew 'opencore-amr'
brew 'ossp-uuid'
brew 'pkg-config'
brew 'postgresql'
brew 'qt5'
brew 'ranger'
brew 'ruby-build'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ripgrep'
brew 'sassc'
brew 'stow'
brew 'tarsnap'
brew 'texi2html'
brew 'tig'
brew 'tmux', args: ['HEAD']
brew 'trash'
brew 'tree'
brew 'uncrustify'
brew 'unixodbc'
brew 'utf8proc'
brew 'vim'
brew 'weechat', args: ['with-curl', 'with-perl', 'with-python', 'with-ruby']
brew 'wxmac'
brew 'xctool'
brew 'yasm'
brew 'kylef/formulae/swiftenv'
cask 'bettertouchtool'
cask 'cloudytabs'
cask 'iterm2'
cask 'owncloud'
cask 'postman'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'skim'
cask 'transmission'
cask 'ubersicht'
cask 'vlc'
mas 'Final Cut Pro', id: 424389933
mas 'External Editors For Photos', id: 1074021862
mas 'Hues', id: 411811718
mas 'Kaleidoscope', id: 587512244
mas 'Flume', id: 792425898
mas 'Jeff', id: 934011232
mas 'Monosnap', id: 540348655
mas 'The Unarchiver', id: 425424353
mas 'Pixelmator', id: 407963104
mas 'DaisyDisk', id: 411643860
mas '1Password', id: 443987910
mas 'Aperture', id: 408981426
mas 'Reeder', id: 880001334
mas 'xScope', id: 889428659
mas 'Characters', id: 536511979
mas 'Redacted', id: 984968384
mas 'Deckset', id: 847496013
mas 'Soulver', id: 413965349
mas 'Bear', id: 1091189122
mas 'Transmit', id: 403388562
mas 'Exporter for Aperture', id: 901489125
mas 'Spark', id: 1176895641
mas 'Slack', id: 803453959
mas 'Polarr Photo Editor', id: 1058273036
mas 'iFlicks 2', id: 731062389
mas 'Compressor', id: 424390742
mas 'Realm Browser', id: 1007457278
mas 'GIF Brewery 3', id: 1081413713
mas 'Numbers', id: 409203825
mas 'Harvest', id: 506189836
